### ISSUE TITLE
Check if Postcard is ready to send after_save

### ISSUE THREAD

**Issue by TimKJones** [edance/gram-gram#27]
Every time a Postcard is updated, check if it's in a valid state to send with Lob. Trigger the job to send it when it is.

**Comment by TimKJones** [comment]
A Postcard is ready to send with Lob if:
1) it has a recipient
2) it has a photo
3) it has a caption
4) it has a stripe_charge_id

**Comment by TimKJones** [comment]
@edance do you think we should require a caption? I guess we don't need to tell people how to send postcards to grandma if they want it to be blank?

**Comment by edance** [comment]
I don't think that a caption needs to be required.
