### ISSUE TITLE
Logout shows me an error page

### ISSUE THREAD

**Issue by TimKJones** [edance/gram-gram#45]
Clicking logout from the header takes me to the heroku error page

<img width="677" alt="Screen Shot 2019-12-01 at 4 23 32 PM" src="https://user-images.githubusercontent.com/950405/69923124-285b3e00-1457-11ea-9b6b-8efab86790d3.png">

When manually navigating to gramgram.app, it then auto-logs me back in and directs me to /photos. Pretty sure I wasn't actually logged out.

**Comment by TimKJones** [comment]
This works locally, but not in production. But I don't think it's worth diving into yet until we get logging properly configured in production.

**Comment by edance** [comment]
This might be fixed now
