### ISSUE TITLE
Landing page CTA button colors should be darker

### ISSUE THREAD

**Issue by TimKJones** [edance/gram-gram#48]
Not sure if darker is the word, maybe less transparent. This is just my opinion, but I don't think the CTA button colors are prominent enough. Any changes should apply to the CTA at the bottom of the page too. 

<img width="649" alt="Screen Shot 2019-12-01 at 4 34 58 PM" src="https://user-images.githubusercontent.com/950405/69923333-dc10fd80-1458-11ea-9add-a95487aea8ec.png">

**Comment by edance** [comment]
Closing this because I changed the text color to black. I think a designer will probably change the whole color scheme anyway
