### ISSUE TITLE
Wrap up Facebook approval process

### ISSUE THREAD

**Issue by TimKJones** [edance/gram-gram#58]
We started the process, but I haven't received any confirmation that we're good to go. We need to make sure this is squared away before launching.

**Comment by TimKJones** [comment]
<img width="872" alt="Screen Shot 2019-12-10 at 3 30 12 PM" src="https://user-images.githubusercontent.com/950405/70578277-1584ef80-1b62-11ea-8bb5-1036ef923a16.png">

FYI @edance - I uploaded the screencasts but never actually clicked "Submit for Review". Just did that; we'll see what happens.

**Comment by edance** [comment]
I submitted again today!
